services:
  frontend:
    container_name: witchs-cauldron-frontend-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    image: witchs-cauldron-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 로그 설정 (옵션)
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # 리소스 제한 (옵션)
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

# 네트워크 설정 (다른 서비스와 연결이 필요한 경우)
networks:
  default:
    name: witchs-cauldron-network
