import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import sharp from 'sharp';

const base = process.env.SMOKE_BASE_URL || 'http://127.0.0.1:3168';
assert.ok(['localhost', '127.0.0.1', '[::1]'].includes(new URL(base).hostname), 'fanart smoke is loopback only');
assert.equal(process.env.FANART_SMOKE_ALLOW_WRITES, 'true', 'explicit disposable test database acknowledgment required');
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ httpCredentials: { username: process.env.ADMIN_BASIC_AUTH_USERNAME || 'fanart-admin', password: process.env.ADMIN_BASIC_AUTH_PASSWORD || 'fanart-local-only' } });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await context.route('**/api/analytics/**', route => route.fulfill({ json: { ok: true } }));
const stamp = Date.now().toString();
const title = `테스트 작품 ${stamp}`;
try {
  const denied = await fetch(`${base}/api/admin/fanart`);
  assert.equal(denied.status, 401);
  await page.goto(`${base}/admin/fanart`);
  await page.getByRole('heading', { name: '팬아트 검수함', exact: true }).waitFor({ timeout: 15000 });
  await page.getByLabel('원문 URL', { exact: true }).fill(`https://cafe.naver.com/moinge/${stamp}`);
  await page.getByLabel('작품 제목', { exact: true }).fill(title);
  await page.getByLabel('작가 표기명', { exact: true }).fill('자체 테스트 작가');
  await page.getByRole('button', { name: '후보 등록', exact: true }).click();
  await page.getByRole('heading', { name: title, exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: '게시 승인', exact: true }).isDisabled(), true);
  await page.getByLabel('외부 사이트 이미지 표시 허락').check();
  await page.getByLabel('크기 조정·WebP 변환 허락').check();
  await page.getByLabel('작가명·원문 링크 표기 허락').check();
  await page.getByLabel('허락 확인일').fill('2026-09-18T12:00');
  await page.getByLabel('허락 증빙 메모').fill('자체 제작 테스트 도형 — 외부 작가 데이터 아님');
  await page.getByLabel('작가의 생성형 AI 미사용 확인일').fill('2026-09-18T12:00');
  await page.getByLabel('운영자 제작 방식 검수').selectOption('confirmed_non_generative');
  await page.getByLabel('운영자 검수일').fill('2026-09-18T12:00');
  await page.getByRole('button', { name: '허락·검수 기록 저장', exact: true }).click();
  await page.getByText('허락·검수 기록을 저장했습니다.', { exact: true }).waitFor();
  const buffer = await sharp({ create: { width: 200, height: 240, channels: 3, background: '#a020f0' } }).png().toBuffer();
  await page.getByLabel('허락받은 이미지 파일').setInputFiles({ name: 'owned-test.png', mimeType: 'image/png', buffer });
  await page.getByRole('button', { name: '이미지 업로드', exact: true }).click();
  await page.getByText('이미지를 준비했습니다.', { exact: true }).waitFor();
  await page.getByRole('button', { name: '게시 승인', exact: true }).click();
  await page.getByText('작업실에 게시했습니다.', { exact: true }).waitFor();
  const publicResponse = await context.request.get(`${base}/api/fanart`);
  const published = (await publicResponse.json()).images.find(image => image.alt === title);
  assert.ok(published);
  assert.deepEqual(Object.keys(published).sort(), ['id', 'src', 'alt', 'credit', 'sourceUrl', 'publishedAt'].sort());
  const media = await context.request.get(`${base}${published.src}`);
  assert.equal(media.status(), 200);
  assert.equal(media.headers()['cache-control'], 'no-store');
  const optimized = await context.request.get(`${base}/_next/image?url=${encodeURIComponent(published.src)}&w=640&q=75`);
  assert.equal(optimized.status(), 400, 'managed images must never enter optimizer cache');
  const gallery = await context.newPage();
  gallery.on('pageerror', error => errors.push(error.message));
  await gallery.goto(base);
  await gallery.getByRole('button', { name: `${title} 크게 보기` }).first().waitFor({ timeout: 20000 });
  await gallery.getByRole('button', { name: `${title} 크게 보기` }).first().click();
  await gallery.getByRole('dialog', { name: '팬아트 상세 보기' }).waitFor();
  assert.equal(await gallery.getByRole('link', { name: '원문 보기' }).last().getAttribute('href'), published.sourceUrl);
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: '게시 철회', exact: true }).click();
  await page.getByText('게시를 철회했습니다.', { exact: true }).waitFor();
  await page.getByText('처리 기록', { exact: true }).click();
  await page.getByText(/· withdrawn ·/).waitFor({ timeout: 3000 });
  assert.equal((await context.request.get(`${base}${published.src}`)).status(), 404);
  await gallery.evaluate(() => window.dispatchEvent(new Event('focus')));
  await gallery.getByRole('button', { name: `${title} 크게 보기` }).waitFor({ state: 'hidden' });
  assert.equal((await (await context.request.get(`${base}/api/fanart`)).json()).images.some(image => image.id === published.id), false);
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'mobile admin overflow');
  assert.deepEqual(errors, []);
  console.log('PASS fanart browser: create, permission/review, upload, publish, gallery/modal, optimizer denial, withdraw, mobile');
} finally {
  await browser.close();
}
